logout:
    path: /logout
product:
    path:     /product
    controller: App\Controller\DefaultController::index
show:
    path:     /product/show/{id}
    controller: App\Controller\DefaultController::show